### **Analisando Artigos**

In [7]:
# Importando Blibiotecas
import os
import json
import pandas as pd

In [ ]:
# Definindo a query
query = (
    "([videofluoroscopy] OR [videofluoroscopic swallowing study] OR "
    "[videofluoroscopic swallowing studies] OR [VFSS] OR "
    "[modified barium swallow] OR [MBS] OR [barium swallow study]) "
    "AND "
    "([artificial intelligence] OR [machine learning] OR [deep learning] OR "
    "[neural network] OR [convolutional neural network] OR [CNN] OR "
    "[computer vision] OR [image recognition] OR [video analysis] OR "
    "[object detection] OR [pose estimation] OR [optical flow] OR "
    "[segmentation] OR [tracking] OR [classification] OR [prediction]) "
    "AND "
    "([swallowing] OR [deglutition] OR [dysphagia] OR "
    "[aspiration] OR [penetration] OR [pharyngeal] OR [laryngeal] OR "
    "[hyoid] OR [epiglottis] OR [bolus] OR "
    "[upper esophageal sphincter] OR [UES] OR "
    "[swallowing kinematics] OR [swallowing timing] OR [swallowing events])"
)

In [11]:
# Fazendo a busca

output_json = r"C:\Users\vinic\OneDrive\Documentos\0300_Projetos\INCA\vfss_to_docker\data\artigos\vfss_ai_papers.json"

ret = os.system(
    f'findpapers search "{output_json}" -q "{query}"'
)

if ret:
    print("ERRO no comando")
else:
    print("Seleção Concluída!")

Seleção Concluída!

In [4]:
# Examinando artigos encontrados

with open(output_json, "r", encoding="utf-8") as f:
    papers = json.load(f)

df = pd.DataFrame(papers["papers"])

print(f"{len(df)} artigos encontrados")
df.head()

2541 artigos encontrados

,abstract,authors,categories,citations,comments,databases,doi,keywords,number_of_pages,pages,publication,publication_date,selected,title,urls
0,PURPOSE OBJECTIVE Patients with Zenker's diver...,"[Daniel Ostler-Mildner, Alissa Jell, Matthias ...",None,None,None,[PubMed],None,"[N Biomedical acoustics, N Dysphagia, N Comput...",NaN,None,"{'category': 'Journal', 'cite_score': None, 'i...",2026-06-03,None,Deep learning for early detection of Zenker's ...,[]
1,BACKGROUND BACKGROUND Accurate real-time predi...,"[Pallavi M Sawant, Rajesh B Ghongade]",None,None,None,[PubMed],None,"[N BiLSTM, N diabetes management, N blood gluc...",NaN,None,"{'category': 'Journal', 'cite_score': None, 'i...",2026-06-03,None,Diabetes Management Through Glucose Dynamics A...,[]
2,To evaluate the feasibility of a smartphone-ba...,"[Yong Jae Na, Jun Hyeok Lee, Eunyoung Choi, Jo...",None,None,None,[PubMed],None,"[N Swallowing disorder, N Artificial intellige...",NaN,None,"{'category': 'Journal', 'cite_score': None, 'i...",2026-06-02,None,Deep Learning-Based Acoustic Screening for Pen...,[]
3,BACKGROUND BACKGROUND Deep learning integrated...,"[Chenyu Jin, Bei Pei, Ren Zhou, Shuang Cao, Yu...",None,None,None,[PubMed],None,"[N Artificial Intelligence, N Deep learning, N...",NaN,None,"{'category': 'Journal', 'cite_score': None, 'i...",2026-06-01,None,A two-step deep learning framework for predict...,[]
4,BACKGROUND BACKGROUND Head and neck squamous c...,"[Xiaokai You, Qiao Jiang, Wenrui Xue, Zhenyong...",None,None,None,[PubMed],None,"[N Biomarker-driven patient selection, N Respo...",NaN,105410,"{'category': 'Journal', 'cite_score': None, 'i...",2026-05-31,None,Neoadjuvant Immunotherapy in Locally Advanced ...,[]

In [5]:
df.columns.tolist()

cols = [c for c in df.columns if any(
    k in c.lower()
    for k in ["title", "author", "year", "doi", "abstract"]
)]

df[cols].head()

,abstract,authors,doi,title
0,PURPOSE OBJECTIVE Patients with Zenker's diver...,"[Daniel Ostler-Mildner, Alissa Jell, Matthias ...",None,Deep learning for early detection of Zenker's ...
1,BACKGROUND BACKGROUND Accurate real-time predi...,"[Pallavi M Sawant, Rajesh B Ghongade]",None,Diabetes Management Through Glucose Dynamics A...
2,To evaluate the feasibility of a smartphone-ba...,"[Yong Jae Na, Jun Hyeok Lee, Eunyoung Choi, Jo...",None,Deep Learning-Based Acoustic Screening for Pen...
3,BACKGROUND BACKGROUND Deep learning integrated...,"[Chenyu Jin, Bei Pei, Ren Zhou, Shuang Cao, Yu...",None,A two-step deep learning framework for predict...
4,BACKGROUND BACKGROUND Head and neck squamous c...,"[Xiaokai You, Qiao Jiang, Wenrui Xue, Zhenyong...",None,Neoadjuvant Immunotherapy in Locally Advanced ...

In [6]:
df.to_excel(
    r"..\data\artigos\vfss_ai_papers.xlsx",
    index=False
)

print("Arquivo salvo!")

Arquivo salvo!