### **Analisando Artigos**

In [ ]:
# Importando Blibiotecas
import os
import json
import pandas as pd

In [2]:
# Definindo query
query = """([videofluoroscopy] OR [videofluoroscopic swallowing study] OR [videofluoroscopic swallowing studies] OR [VFSS] OR [modified barium swallow] OR [MBS] OR [dysphagia]) AND ([artificial intelligence] OR [machine learning] OR [deep learning] OR [computer vision] OR [neural network])"""

In [ ]:
# Fazendo a busca

output_json = r"C:\Users\vinic\OneDrive\Documentos\0300_Projetos\INCA\vfss_to_docker\data\artigos\vfss_ai_papers.json"

ret = os.system(
    f'findpapers search "{output_json}" -q "{query}"'
)

if ret:
    print("ERRO no comando")
else:
    print("Seleção Concluída!")

Seleção Concluída!

In [9]:
# Examinando artigos encontrados

with open(output_json, "r", encoding="utf-8") as f:
    papers = json.load(f)

df = pd.DataFrame(papers["papers"])

print(f"{len(df)} artigos encontrados")
df.head()

383 artigos encontrados

,abstract,authors,categories,citations,comments,databases,doi,keywords,number_of_pages,pages,publication,publication_date,selected,title,urls
0,PURPOSE OBJECTIVE Patients with Zenker's diver...,"[Daniel Ostler-Mildner, Alissa Jell, Matthias ...",None,None,None,[PubMed],None,"[N Deep learning, N Biomedical acoustics, N Co...",NaN,None,"{'category': 'Journal', 'cite_score': None, 'i...",2026-06-03,None,Deep learning for early detection of Zenker's ...,[]
1,To evaluate the feasibility of a smartphone-ba...,"[Yong Jae Na, Jun Hyeok Lee, Eunyoung Choi, Jo...",None,None,None,[PubMed],None,"[N Swallowing disorder, N Artificial intellige...",NaN,None,"{'category': 'Journal', 'cite_score': None, 'i...",2026-06-02,None,Deep Learning-Based Acoustic Screening for Pen...,[]
2,BACKGROUND UNASSIGNED Dysphagia is a highly pr...,"[Hairong Yu, Jingyi Huang, Tianchi Zhuang, Jie...",None,None,None,[PubMed],None,"[N orthogonal experiment, N screen, N stroke, ...",12.0,1-12,"{'category': 'Journal', 'cite_score': None, 'i...",2026-05-30,None,Optimizing cervical breath sound acquisition p...,[]
3,BACKGROUND BACKGROUND Bictegravir/Emtricitabin...,"[Yuxin Xie, Yawen Luo, Yinghua Chen, Guoqing S...",None,None,None,[PubMed],None,"[N Pancreatitis, N Adverse drug events (ADEs),...",NaN,None,"{'category': 'Journal', 'cite_score': None, 'i...",2026-05-30,None,Post-marketing safety profile of bictegravir/e...,[]
4,"' Neurological disorders, such as Parkinsons d...","[Daniela Gasperini, Francesco Pierotti, Luigi ...",None,None,None,[PubMed],None,"[N clinical validation, N neurogenic dysphagia...",NaN,None,"{'category': 'Journal', 'cite_score': None, 'i...",2026-05-28,None,Wearable sensors for monitoring neurogenic dys...,[]

In [10]:
df.columns.tolist()

cols = [c for c in df.columns if any(
    k in c.lower()
    for k in ["title", "author", "year", "doi", "abstract"]
)]

df[cols].head()

,abstract,authors,doi,title
0,PURPOSE OBJECTIVE Patients with Zenker's diver...,"[Daniel Ostler-Mildner, Alissa Jell, Matthias ...",None,Deep learning for early detection of Zenker's ...
1,To evaluate the feasibility of a smartphone-ba...,"[Yong Jae Na, Jun Hyeok Lee, Eunyoung Choi, Jo...",None,Deep Learning-Based Acoustic Screening for Pen...
2,BACKGROUND UNASSIGNED Dysphagia is a highly pr...,"[Hairong Yu, Jingyi Huang, Tianchi Zhuang, Jie...",None,Optimizing cervical breath sound acquisition p...
3,BACKGROUND BACKGROUND Bictegravir/Emtricitabin...,"[Yuxin Xie, Yawen Luo, Yinghua Chen, Guoqing S...",None,Post-marketing safety profile of bictegravir/e...
4,"' Neurological disorders, such as Parkinsons d...","[Daniela Gasperini, Francesco Pierotti, Luigi ...",None,Wearable sensors for monitoring neurogenic dys...

In [16]:
df.to_excel(
    r"..\data\artigos\vfss_ai_papers.xlsx",
    index=False
)

print("Arquivo salvo!")

Arquivo salvo!